---
- name: Install kubernetes GPG key
  apt_key:
    url: "{{ kubernetes_url_key }}" 
    state: present

- name: Create kubernetes repo 
  apt_repository:
    repo: "{{ kubernetes_url_repo }}"
    state: present
    filename: kubernetes
    update_cache: yes
